
using System.ComponentModel;
using Shiron.Docs.Engine;
using Spectre.Console;
using Spectre.Console.Cli;

namespace Shiron.Docs.Cli.Commands;

[Description("Initializes a new Shiron Docs documentation site. Supports interactive mode.")]
public sealed class CommandInit(IConfigManager configManager) : AsyncCommand<CommandInit.Settings> {
    private readonly IConfigManager _configManager = configManager;

    public class Settings : CommandSettings {
    }

    public override async Task<int> ExecuteAsync(CommandContext context, Settings settings, CancellationToken cancellationToken) {
        AnsiConsole.MarkupLine($"{CLIConstants.Prefix} [bold aqua]Initializing Shiron Docs configuration...[/]");
        var documentationDir = await AnsiConsole.AskAsync<string>("Where would you like to store your documentation pages? ", "docs");
        var outputDir = await AnsiConsole.AskAsync<string>("Where would you like to output the static site? ", "docs/_site");
        var appName = await AnsiConsole.AskAsync<string>("What is the name of your documentation site? ", "My Documentation Site");
        var appFooter = await AnsiConsole.AskAsync<string>("What footer text would you like to display on your documentation site? ", "Generated by Shiron Docs");
        var includes = await AnsiConsole.AskAsync<string>("Where do your project files reside? (supports glob patterns)", "src/**/*.csproj");

        var config = new Config {
            OutputDirectory = outputDir,
            AppName = appName,
            AppFooter = appFooter,
            AppVersion = "1.0.0",

            Includes = [includes],
            Excludes = []
        };
        await _configManager.SaveConfigAsync(config);

        if (!Directory.Exists(documentationDir)) {
            _ = Directory.CreateDirectory(documentationDir);
        }

        AnsiConsole.MarkupLine($"{CLIConstants.Prefix} [bold green]Configuration initialized successfully![/]");

        return 0;
    }
}
